### ISSUE TITLE
How to see GPU metrics in the developer view logged in as a regular user?

### ISSUE THREAD

**Issue by hfwen0502** [rh-ecosystem-edge/console-plugin-nvidia-gpu#50]
If we log in as cluster-admin in OCP 4.10, we can see all the DCGM_x metrics exposed by the Nvidia DCGM exporter.
<img width="423" alt="image" src="https://user-images.githubusercontent.com/14792895/195698162-ea9a76b9-4480-4c10-bae0-1aca26a00fea.png">

How do we see these metrics if now we log in as a non-privileged user  in the developer view?
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/14792895/195697968-ec928a2e-5d86-4369-bbb5-5ade256e18d6.png">

What are the steps we need to enable the GPU metrics monitoring for a given user?

**Comment by hfwen0502** [comment]
I wonder if it is due to the reason below:

<img width="797" alt="image" src="https://user-images.githubusercontent.com/14792895/195744705-8347b19b-63f5-4980-8213-add73669185e.png">

**Comment by jelkosz** [comment]
@fabiendupont do you happen to know how to expose those metrics to non privileged users?

**Comment by fabiendupont** [comment]
@mresvanis, do you know?

**Comment by mresvanis** [comment]
@hfwen0502 is the NVIDIA GPU operator (and consequently the DCGM Exporter) deployed in the `hwen` namespace? If not you can select the namespace of the NVIDIA GPU operator and you should be able to view the metrics via selecting `Custom Query` and then start typing `dcgm_` to see the available metrics and construct your query.

**Comment by mresvanis** [comment]
In that case, I think the reason your user is not allowed to view those metrics is that, by default, they are scraped by the cluster monitoring stack instead of the user workload monitoring stack. 

As a workaround (and by keeping the additional `view` role on your user) I would suggest to try the following:
- (if you haven't already done so) enable the user workload monitoring stack, by following [these](https://docs.openshift.com/container-platform/4.10/monitoring/enabling-monitoring-for-user-defined-projects.html#enabling-monitoring-for-user-defined-projects_enabling-monitoring-for-user-defined-projects) instructions
- disable the `nvidia-gpu-operator` cluster monitoring metrics, via editing the `nvidia-gpu-operator` namespace `metadata.label` `openshift.io/cluster-monitoring: "true"` -> `openshift.io/cluster-monitoring: "false"`

**Comment by hfwen0502** [comment]
@mresvanis Your initial solution just works. There was something wrong with the DCGM pods in my cluster. So the only step to enable users to query GPU metrics (at least in OCP 4.10) is to allow them to view the project where Nvidia GPU operator is installed. Thanks so much for the guidance and I will close this issue.

**Comment by hfwen0502** [comment]
Reopen this issue....

Though we can query GPU metrics using a non-privileged user id by switching to the nvidia-gpu-operator project, the GPU metrics are not correlated to our specific project (i.e.: hfwen), unlike the core OCP components. Is there a way that we can query GPU metrics only specific to a user's project?

**Comment by mresvanis** [comment]
When the pods scheduled to GPU nodes explicitly [request](https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/) a GPU resource, i.e.:

```yaml
resources:
  limits:
    "nvidia.com/gpu": 1
```

the DCGM exporter metrics will contain the following additional labels `exported_container`, `exported_namespace`, `exported_pod`. A user could query for metrics for their namespace of choice with a PromQL query like:

```
DCGM_FI_PROF_GR_ENGINE_ACTIVE{exported_namespace="hfwen"}
```

But I don't see how we could restrict the users viewing GPU metrics regarding a single namespace, given that all metrics are generated by the DCGM exporter in the `nvidia-gpu-operator` namespace and the user needs to be bound to the `view` role for the latter.
